HEADERS += \
    dialogs/dialogs.h \
    dialogs/tools/dialogtriangle.h \
    dialogs/tools/dialogtool.h \
    dialogs/tools/dialogsplinepath.h \
    dialogs/tools/dialogspline.h \
    dialogs/tools/dialogsinglepoint.h \
    dialogs/tools/dialogshoulderpoint.h \
    dialogs/tools/dialogpointofintersection.h \
    dialogs/tools/dialogpointofcontact.h \
    dialogs/tools/dialognormal.h \
    dialogs/tools/dialoglineintersect.h \
    dialogs/tools/dialogline.h \
    dialogs/tools/dialogheight.h \
    dialogs/tools/dialogendline.h \
    dialogs/tools/dialogdetail.h \
    dialogs/tools/dialogbisector.h \
    dialogs/tools/dialogarc.h \
    dialogs/tools/dialogalongline.h \
    dialogs/tools/dialogcutspline.h \
    dialogs/tools/dialogcutsplinepath.h \
    dialogs/tools/dialoguniondetails.h \
    dialogs/tools/dialogcutarc.h \
    dialogs/tools/dialogeditwrongformula.h \
    dialogs/tools/dialoglineintersectaxis.h \
    dialogs/app/dialogincrements.h \
    dialogs/app/dialoghistory.h \
    dialogs/app/configdialog.h \
    dialogs/app/configpages/pages.h \
    dialogs/app/dialogpatternproperties.h \
    dialogs/app/dialogmeasurements.h \
    dialogs/app/dialogstandardmeasurements.h \
    dialogs/app/dialogindividualmeasurements.h \
    dialogs/app/dialogaboutapp.h \
    dialogs/app/dialogpatternxmledit.h \
    dialogs/app/configpages/configurationpage.h \
    dialogs/app/configpages/patternpage.h \
    dialogs/app/configpages/communitypage.h \
    dialogs/app/configpages/pathpage.h \
    dialogs/app/dialogundo.h \
    dialogs/tools/dialogcurveintersectaxis.h

SOURCES += \
    dialogs/tools/dialogtriangle.cpp \
    dialogs/tools/dialogtool.cpp \
    dialogs/tools/dialogsplinepath.cpp \
    dialogs/tools/dialogspline.cpp \
    dialogs/tools/dialogsinglepoint.cpp \
    dialogs/tools/dialogshoulderpoint.cpp \
    dialogs/tools/dialogpointofintersection.cpp \
    dialogs/tools/dialogpointofcontact.cpp \
    dialogs/tools/dialognormal.cpp \
    dialogs/tools/dialoglineintersect.cpp \
    dialogs/tools/dialogline.cpp \
    dialogs/tools/dialogheight.cpp \
    dialogs/tools/dialogendline.cpp \
    dialogs/tools/dialogdetail.cpp \
    dialogs/tools/dialogbisector.cpp \
    dialogs/tools/dialogarc.cpp \
    dialogs/tools/dialogalongline.cpp \
    dialogs/tools/dialogcutspline.cpp \
    dialogs/tools/dialogcutsplinepath.cpp \
    dialogs/tools/dialoguniondetails.cpp \
    dialogs/tools/dialogcutarc.cpp \
    dialogs/tools/dialogeditwrongformula.cpp \
    dialogs/tools/dialoglineintersectaxis.cpp \
    dialogs/app/dialogincrements.cpp \
    dialogs/app/dialoghistory.cpp \
    dialogs/app/configdialog.cpp \
    dialogs/app/dialogpatternproperties.cpp \
    dialogs/app/dialogmeasurements.cpp \
    dialogs/app/dialogstandardmeasurements.cpp \
    dialogs/app/dialogindividualmeasurements.cpp \
    dialogs/app/dialogaboutapp.cpp \
    dialogs/app/dialogpatternxmledit.cpp \
    dialogs/app/configpages/configurationpage.cpp \
    dialogs/app/configpages/patternpage.cpp \
    dialogs/app/configpages/communitypage.cpp \
    dialogs/app/configpages/pathpage.cpp \
    dialogs/app/dialogundo.cpp \
    dialogs/tools/dialogcurveintersectaxis.cpp

FORMS += \
    dialogs/tools/dialogtriangle.ui \
    dialogs/tools/dialogsplinepath.ui \
    dialogs/tools/dialogspline.ui \
    dialogs/tools/dialogsinglepoint.ui \
    dialogs/tools/dialogshoulderpoint.ui \
    dialogs/tools/dialogpointofintersection.ui \
    dialogs/tools/dialogpointofcontact.ui \
    dialogs/tools/dialognormal.ui \
    dialogs/tools/dialoglineintersect.ui \
    dialogs/tools/dialogline.ui \
    dialogs/tools/dialogheight.ui \
    dialogs/tools/dialogendline.ui \
    dialogs/tools/dialogdetail.ui \
    dialogs/tools/dialogbisector.ui \
    dialogs/tools/dialogarc.ui \
    dialogs/tools/dialogalongline.ui \
    dialogs/tools/dialogcutspline.ui \
    dialogs/tools/dialogcutsplinepath.ui \
    dialogs/tools/dialoguniondetails.ui \
    dialogs/tools/dialogcutarc.ui \
    dialogs/tools/dialogeditwrongformula.ui \
    dialogs/tools/dialoglineintersectaxis.ui \
    dialogs/app/dialogincrements.ui \
    dialogs/app/dialoghistory.ui \
    dialogs/app/dialogpatternproperties.ui \
    dialogs/app/dialogmeasurements.ui \
    dialogs/app/dialogstandardmeasurements.ui \
    dialogs/app/dialogindividualmeasurements.ui \
    dialogs/app/dialogaboutapp.ui \
    dialogs/app/dialogpatternxmledit.ui \
    dialogs/app/dialogundo.ui \
    dialogs/tools/dialogcurveintersectaxis.ui
