#!/bin/sh

# Commit hook. Helps update bookmark.
# Put this file in your path.
#
# Edit file .hg/hgrc
#
# [hooks]
# outgoing = outgoinghook

sh -c "hg push -f git+ssh://git@github.com/dismine/Valentina.git" &

exit 0;
