[Icon Theme]
Name=win.icon.theme
Comment=win.icon.theme for valentina 
Inherits=gnome,hicolor
Example=x-directory-normal

#Directories
Directories=16x16/actions,24x24/actions,32x32/actions,32x32/emblems 

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[24x24/actions]
Size=24
Context=Actions
Type=Fixed

[32x32/actions]
Size=32
Context=Actions
Type=Fixed

[32x32/emblemss]
Size=32
Context=Emblems
Type=Fixed

