HEADERS += \
    src/tools/vtooldetail.h \
    src/tools/vdatatool.h \
    src/tools/vabstracttool.h \
    src/tools/tools.h \
    src/tools/drawTools/vtooltriangle.h \
    src/tools/drawTools/vtoolsplinepath.h \
    src/tools/drawTools/vtoolspline.h \
    src/tools/drawTools/vtoolsinglepoint.h \
    src/tools/drawTools/vtoolshoulderpoint.h \
    src/tools/drawTools/vtoolpointofintersection.h \
    src/tools/drawTools/vtoolpointofcontact.h \
    src/tools/drawTools/vtoolpoint.h \
    src/tools/drawTools/vtoolnormal.h \
    src/tools/drawTools/vtoollinepoint.h \
    src/tools/drawTools/vtoollineintersect.h \
    src/tools/drawTools/vtoolline.h \
    src/tools/drawTools/vtoolheight.h \
    src/tools/drawTools/vtoolendline.h \
    src/tools/drawTools/vtoolbisector.h \
    src/tools/drawTools/vtoolarc.h \
    src/tools/drawTools/vtoolalongline.h \
    src/tools/drawTools/vdrawtool.h \
    src/tools/drawTools/drawtools.h \
    src/tools/nodeDetails/vnodesplinepath.h \
    src/tools/nodeDetails/vnodespline.h \
    src/tools/nodeDetails/vnodepoint.h \
    src/tools/nodeDetails/vnodearc.h \
    src/tools/nodeDetails/vabstractnode.h \
    src/tools/nodeDetails/nodedetails.h \
    src/tools/drawTools/vtoolcutspline.h \
    src/tools/drawTools/vtoolcutsplinepath.h

SOURCES += \
    src/tools/vtooldetail.cpp \
    src/tools/vdatatool.cpp \
    src/tools/vabstracttool.cpp \
    src/tools/drawTools/vtooltriangle.cpp \
    src/tools/drawTools/vtoolsplinepath.cpp \
    src/tools/drawTools/vtoolspline.cpp \
    src/tools/drawTools/vtoolsinglepoint.cpp \
    src/tools/drawTools/vtoolshoulderpoint.cpp \
    src/tools/drawTools/vtoolpointofintersection.cpp \
    src/tools/drawTools/vtoolpointofcontact.cpp \
    src/tools/drawTools/vtoolpoint.cpp \
    src/tools/drawTools/vtoolnormal.cpp \
    src/tools/drawTools/vtoollinepoint.cpp \
    src/tools/drawTools/vtoollineintersect.cpp \
    src/tools/drawTools/vtoolline.cpp \
    src/tools/drawTools/vtoolheight.cpp \
    src/tools/drawTools/vtoolendline.cpp \
    src/tools/drawTools/vtoolbisector.cpp \
    src/tools/drawTools/vtoolarc.cpp \
    src/tools/drawTools/vtoolalongline.cpp \
    src/tools/drawTools/vdrawtool.cpp \
    src/tools/nodeDetails/vnodesplinepath.cpp \
    src/tools/nodeDetails/vnodespline.cpp \
    src/tools/nodeDetails/vnodepoint.cpp \
    src/tools/nodeDetails/vnodearc.cpp \
    src/tools/nodeDetails/vabstractnode.cpp \
    src/tools/drawTools/vtoolcutspline.cpp \
    src/tools/drawTools/vtoolcutsplinepath.cpp
